//#define CONFIG_FREERTOS_IDLE_TIME_BEFORE_SLEEP 2 // must be > 1 to compile!! 
//#define CONFIG_FREERTOS_USE_TICKLESS_IDLE 1 
//#define CONFIG_PM_USE_RTC_TIMER_REF 1
#define CONFIG_PM_ENABLE 1 
#define CONFIG_FREERTOS_MAX_TASK_NAME_LEN 9
