services:

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: fs_mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosquitto_data:/mosquitto/data
    restart: unless-stopped
    networks:
      - iot-network

  influxdb:
    image: influxdb:2.7
    container_name: fs_influxdb
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: adminpassword
      DOCKER_INFLUXDB_INIT_ORG: floating_sensor
      DOCKER_INFLUXDB_INIT_BUCKET: floating_sensor
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: fs-dev-token
    volumes:
      - influxdb_data:/var/lib/influxdb2
    restart: unless-stopped
    networks:
      - iot-network

volumes:
  mosquitto_data:
  influxdb_data:

networks:
  iot-network:
    driver: bridge
